name: cmot-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - networkx
    - opencv-python
    - tqdm
    - numpy<2
    - scipy
    - polars
    - stardist
    - tensorflow-cpu
    - black[jupyter]==24.10.0
    - isort==5.13.2
    - torch
    - torchvision
    - torchaudio
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - --find-links https://data.pyg.org/whl/torch-2.5.0+cu124.html
    - -e /home/klettl/Development/github/overlap-tracking
    - -e /home/klettl/Development/github/core-data-utils
    - pre-commit
