name: data-preparation_default
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - opencv-python
    - git+https://github.com/lettlini/core-data-utils
    - polars
    - numpy
    - toml
    - networkx
    - cpuonly
    - pytorch
